#!/usr/bin/env bash
# =============================================================================
# Ghost Sphere — Node installer (one command, fully automatic)
# Developed by Ghost OS
#
# Does EVERYTHING in a single run:
#   1. installs Docker (if missing) and waits for the daemon
#   2. removes any previous node container (frees the port — no EADDRINUSE)
#   3. opens the node port in the firewall (ufw / firewalld)
#   4. writes /opt/ghost-sphere-node/{.env,docker-compose.yml}
#   5. checks the port is free, pulls the image and starts the node
#   6. streams the live log so you watch it come online
#
# Usage (copy this exact line from Ghost Sphere → Nodes → Create):
#   SECRET_KEY="<paste>" bash <(curl -Ls https://raw.githubusercontent.com/SKINOREZZZ101/SPHEREGHOST/main/scripts/install-node.sh)
# Optional: NODE_PORT=2222 (default). Use another port if 2222 is taken.
# =============================================================================
set -euo pipefail

GHOST="\033[38;5;141m"; CYAN="\033[38;5;44m"; GREEN="\033[38;5;48m"; YEL="\033[38;5;221m"; RED="\033[38;5;203m"; DIM="\033[2m"; NC="\033[0m"
NODE_DIR="/opt/ghost-sphere-node"
NODE_PORT="${NODE_PORT:-2222}"
IMAGE="${NODE_IMAGE:-remnawave/node:latest}"

log()  { echo -e "${CYAN}»${NC} $*"; }
ok()   { echo -e "${GREEN}✓${NC} $*"; }
warn() { echo -e "${YEL}!${NC} $*"; }
err()  { echo -e "${RED}✗${NC} $*"; }

banner() {
  echo -e "${GHOST}"
  echo "   ░██████╗ ██╗  ██╗ ░█████╗  ░██████╗ ████████╗"
  echo "   ██╔════╝ ██║  ██║ ██╔══██╗ ██╔════╝ ╚══██╔══╝   Ghost Sphere Node"
  echo "   ██║  ██╗ ███████║ ██║  ██║ ╚█████╗     ██║      by Ghost OS"
  echo "   ╚██████╔╝██║  ██║ ╚██████╔╝ ██████╔╝   ██║"
  echo -e "    ╚═════╝ ╚═╝  ╚═╝  ╚═════╝  ╚═════╝    ╚═╝${NC}"
  echo
}

need_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    err "Запустите под root (sudo). / Please run as root (sudo)."
    exit 1
  fi
}

# Pick the available compose command (v2 plugin preferred).
compose() {
  if docker compose version >/dev/null 2>&1; then
    docker compose "$@"
  else
    docker-compose "$@"
  fi
}

ensure_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    log "Устанавливаю Docker… / Installing Docker…"
    curl -fsSL https://get.docker.com | sh >/dev/null 2>&1 || curl -fsSL https://get.docker.com | sh
  fi
  systemctl enable --now docker >/dev/null 2>&1 || true
  log "Жду демон Docker… / Waiting for the Docker daemon…"
  local i
  for i in $(seq 1 30); do
    if docker info >/dev/null 2>&1; then ok "Docker готов. / Docker is ready."; return 0; fi
    sleep 1
  done
  err "Docker daemon не стартовал. / Docker daemon did not start."
  exit 1
}

# Remove every previous node container so nothing is still holding the port.
cleanup_old() {
  log "Убираю прежние контейнеры ноды… / Removing previous node containers…"
  (cd "${NODE_DIR}" 2>/dev/null && compose down --remove-orphans >/dev/null 2>&1) || true
  docker rm -f ghost-sphere-node host-sphere-node remnanode >/dev/null 2>&1 || true
  # Kill ANY container started from the node image (catches duplicates with other names).
  local olds
  olds="$(docker ps -aq --filter "ancestor=${IMAGE}" 2>/dev/null || true)"
  if [[ -n "${olds}" ]]; then docker rm -f ${olds} >/dev/null 2>&1 || true; fi
  sleep 1
}

# Print whatever is listening on NODE_PORT (empty if free).
port_listener() {
  if command -v ss >/dev/null 2>&1; then
    ss -ltnp 2>/dev/null | grep -E "[:.]${NODE_PORT}\b" || true
  elif command -v netstat >/dev/null 2>&1; then
    netstat -ltnp 2>/dev/null | grep -E "[:.]${NODE_PORT}\b" || true
  fi
}

preflight_port() {
  local who
  who="$(port_listener)"
  if [[ -n "${who}" ]]; then
    err "Порт ${NODE_PORT} уже занят. / Port ${NODE_PORT} is already in use."
    echo -e "${DIM}${who}${NC}"
    echo
    echo -e "  Что делать / What to do:"
    echo -e "   • если это старый docker-контейнер — удалите его: ${CYAN}docker ps; docker rm -f <имя>${NC}"
    echo -e "   • если это другой сервис (например SSH на 2222) — выберите другой порт:"
    echo -e "     ${CYAN}NODE_PORT=2223 SECRET_KEY=\"...\" bash <(curl -Ls https://raw.githubusercontent.com/SKINOREZZZ101/SPHEREGHOST/main/scripts/install-node.sh)${NC}"
    echo -e "     затем в панели: Ноды → нода → Настройки → Порт = 2223 → Сохранить."
    exit 1
  fi
}

write_files() {
  mkdir -p "${NODE_DIR}"
  cat > "${NODE_DIR}/.env" <<EOF
### Generated by Ghost Sphere — $(date -u +%Y-%m-%dT%H:%M:%SZ)
SECRET_KEY=${SECRET_KEY}
NODE_PORT=${NODE_PORT}
EOF
  chmod 600 "${NODE_DIR}/.env"
  cat > "${NODE_DIR}/docker-compose.yml" <<EOF
services:
  remnanode:
    image: ${IMAGE}
    container_name: ghost-sphere-node
    hostname: ghost-sphere-node
    restart: always
    network_mode: host
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
EOF
  ok "Конфиг записан в ${NODE_DIR}. / Config written to ${NODE_DIR}."
}

open_firewall() {
  if command -v ufw >/dev/null 2>&1; then
    ufw allow "${NODE_PORT}/tcp" >/dev/null 2>&1 || true
    ok "Порт ${NODE_PORT}/tcp открыт (ufw). / Port opened (ufw)."
  fi
  if command -v firewall-cmd >/dev/null 2>&1; then
    firewall-cmd --permanent --add-port="${NODE_PORT}/tcp" >/dev/null 2>&1 || true
    firewall-cmd --reload >/dev/null 2>&1 || true
    ok "Порт ${NODE_PORT}/tcp открыт (firewalld). / Port opened (firewalld)."
  fi
}

verify_running() {
  sleep 5
  local state restarting
  state="$(docker inspect -f '{{.State.Status}}' ghost-sphere-node 2>/dev/null || echo missing)"
  restarting="$(docker inspect -f '{{.State.Restarting}}' ghost-sphere-node 2>/dev/null || echo false)"
  if [[ "${state}" != "running" || "${restarting}" == "true" ]]; then
    err "Нода не стартовала (статус: ${state}). / Node failed to start (status: ${state})."
    if compose logs --tail=60 2>/dev/null | grep -qi 'EADDRINUSE'; then
      echo
      err "Порт ${NODE_PORT} занят (EADDRINUSE). / Port ${NODE_PORT} is in use (EADDRINUSE)."
      echo -e "${DIM}$(port_listener)${NC}"
      echo -e "  Перезапустите с другим портом: ${CYAN}NODE_PORT=2223 SECRET_KEY=\"...\" bash <(curl -Ls .../install-node.sh)${NC}"
      echo -e "  и укажите тот же порт в панели (Ноды → нода → Настройки → Порт)."
    else
      compose logs --tail=40 || true
    fi
    exit 1
  fi
}

main() {
  banner
  need_root

  if [[ -z "${SECRET_KEY:-}" ]]; then
    err "SECRET_KEY не задан. / SECRET_KEY is not set."
    echo -e "  Скопируйте команду целиком из Ghost Sphere → Ноды → Создать."
    echo -e "  Copy the full command from Ghost Sphere → Nodes → Create."
    exit 1
  fi

  ensure_docker
  write_files
  cleanup_old
  open_firewall
  preflight_port

  cd "${NODE_DIR}"
  log "Загружаю образ ноды (может занять 1–2 мин)… / Pulling node image (may take 1–2 min)…"
  compose pull
  log "Запускаю ноду… / Starting the node…"
  compose up -d --remove-orphans

  verify_running

  echo
  ok "Нода запущена и слушает порт ${NODE_PORT}. / Node is up and listening on ${NODE_PORT}."
  echo -e "${DIM}— Живой лог (≈20с), затем выход. Нода продолжит работать в фоне. —${NC}"
  echo -e "${DIM}— Live log (~20s), then exit. The node keeps running in the background. —${NC}"
  echo
  timeout 20 compose logs -f --tail=40 2>/dev/null || true

  echo
  echo -e "${GREEN}════════════════════════════════════════════════════════════════${NC}"
  ok "Готово! / Done!"
  echo -e "  1) Убедитесь, что порт ${GHOST}${NODE_PORT}/tcp${NC} открыт для IP вашей панели"
  echo -e "     (в т.ч. в облачном фаерволе провайдера / cloud firewall)."
  echo -e "  2) В панели Ghost Sphere → Ноды нода поднимется в статус ${GREEN}«подключено»${NC}"
  echo -e "     за 30–60 секунд (панель сама подключится по mTLS)."
  echo
  echo -e "  Логи / Logs:  ${CYAN}cd ${NODE_DIR} && docker compose logs -f${NC}"
  echo -e "${GREEN}════════════════════════════════════════════════════════════════${NC}"
}

main "$@"
