#!/usr/bin/env bash
# =============================================================================
# Ghost Sphere — Node installer
# Developed by Ghost OS
#
# Deploys a Remnawave-compatible VPN node (Xray) on a clean server.
# Usage:
#   SECRET_KEY="<paste from Ghost Sphere install wizard>" \
#   bash <(curl -Ls https://raw.githubusercontent.com/SKINOREZZZ101/SPHEREGHOST/main/scripts/install-node.sh)
# =============================================================================
set -euo pipefail

GHOST="\033[38;5;141m"; CYAN="\033[38;5;44m"; GREEN="\033[38;5;48m"; RED="\033[38;5;203m"; NC="\033[0m"
NODE_DIR="/opt/ghost-sphere-node"
NODE_PORT="${NODE_PORT:-2222}"

banner() {
  echo -e "${GHOST}"
  echo "   ░██████╗ ██╗  ██╗ ░█████╗  ░██████╗ ████████╗"
  echo "   ██╔════╝ ██║  ██║ ██╔══██╗ ██╔════╝ ╚══██╔══╝   Ghost Sphere Node"
  echo "   ██║  ██╗ ███████║ ██║  ██║ ╚█████╗     ██║      by Ghost OS"
  echo "   ╚██████╔╝██║  ██║ ╚██████╔╝ ██████╔╝   ██║"
  echo -e "    ╚═════╝ ╚═╝  ╚═╝  ╚═════╝  ╚═════╝    ╚═╝${NC}"
  echo
}

need_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo -e "${RED}Please run as root (sudo).${NC}"; exit 1
  fi
}

ensure_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    echo -e "${CYAN}» Installing Docker…${NC}"
    curl -fsSL https://get.docker.com | sh
    systemctl enable --now docker
  fi
}

write_compose() {
  mkdir -p "${NODE_DIR}"
  cat > "${NODE_DIR}/.env" <<EOF
### Generated by Ghost Sphere
SECRET_KEY=${SECRET_KEY}
NODE_PORT=${NODE_PORT}
EOF
  cat > "${NODE_DIR}/docker-compose.yml" <<'EOF'
services:
  remnanode:
    image: remnawave/node:latest
    container_name: ghost-sphere-node
    hostname: ghost-sphere-node
    restart: always
    network_mode: host
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
EOF
}

main() {
  banner
  need_root
  if [[ -z "${SECRET_KEY:-}" ]]; then
    echo -e "${RED}SECRET_KEY is not set.${NC}"
    echo -e "Copy it from the Ghost Sphere → Nodes → Install Wizard, then run:"
    echo -e "  ${CYAN}SECRET_KEY=\"...\" bash install-node.sh${NC}"
    exit 1
  fi
  ensure_docker
  write_compose
  echo -e "${CYAN}» Starting node on port ${NODE_PORT}…${NC}"
  (cd "${NODE_DIR}" && docker compose up -d)
  echo
  echo -e "${GREEN}✓ Ghost Sphere node is online.${NC}"
  echo -e "  Open port ${NODE_PORT}/tcp for your panel IP, then click "
  echo -e "  ${GHOST}Connect${NC} in Ghost Sphere. The sphere will take it from here."
}

main "$@"
