#!/usr/bin/env bash
# =============================================================================
# Ghost Sphere — Node installer (one command, fully automatic)
# Developed by Ghost OS
#
# Does EVERYTHING in a single run:
#   1. installs Docker (if missing) and waits for the daemon
#   2. opens the node port in the firewall (ufw / firewalld)
#   3. writes /opt/ghost-sphere-node/{.env,docker-compose.yml}
#   4. pulls the node image and starts it
#   5. streams the live log so you watch it come online
#
# Usage (copy this exact line from Ghost Sphere → Nodes → Create):
#   SECRET_KEY="<paste>" bash <(curl -Ls https://raw.githubusercontent.com/SKINOREZZZ101/SPHEREGHOST/main/scripts/install-node.sh)
# Optional: NODE_PORT=2222 (default)
# =============================================================================
set -euo pipefail

GHOST="\033[38;5;141m"; CYAN="\033[38;5;44m"; GREEN="\033[38;5;48m"; YEL="\033[38;5;221m"; RED="\033[38;5;203m"; DIM="\033[2m"; NC="\033[0m"
NODE_DIR="/opt/ghost-sphere-node"
NODE_PORT="${NODE_PORT:-2222}"
IMAGE="${NODE_IMAGE:-remnawave/node:latest}"

log()  { echo -e "${CYAN}»${NC} $*"; }
ok()   { echo -e "${GREEN}✓${NC} $*"; }
warn() { echo -e "${YEL}!${NC} $*"; }
err()  { echo -e "${RED}✗${NC} $*"; }

banner() {
  echo -e "${GHOST}"
  echo "   ░██████╗ ██╗  ██╗ ░█████╗  ░██████╗ ████████╗"
  echo "   ██╔════╝ ██║  ██║ ██╔══██╗ ██╔════╝ ╚══██╔══╝   Ghost Sphere Node"
  echo "   ██║  ██╗ ███████║ ██║  ██║ ╚█████╗     ██║      by Ghost OS"
  echo "   ╚██████╔╝██║  ██║ ╚██████╔╝ ██████╔╝   ██║"
  echo -e "    ╚═════╝ ╚═╝  ╚═╝  ╚═════╝  ╚═════╝    ╚═╝${NC}"
  echo
}

need_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    err "Запустите под root (sudo). / Please run as root (sudo)."
    exit 1
  fi
}

# Pick the available compose command (v2 plugin preferred).
compose() {
  if docker compose version >/dev/null 2>&1; then
    docker compose "$@"
  else
    docker-compose "$@"
  fi
}

ensure_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    log "Устанавливаю Docker… / Installing Docker…"
    curl -fsSL https://get.docker.com | sh >/dev/null 2>&1 || curl -fsSL https://get.docker.com | sh
  fi
  systemctl enable --now docker >/dev/null 2>&1 || true
  log "Жду демон Docker… / Waiting for the Docker daemon…"
  local i
  for i in $(seq 1 30); do
    if docker info >/dev/null 2>&1; then ok "Docker готов. / Docker is ready."; return 0; fi
    sleep 1
  done
  err "Docker daemon не стартовал. / Docker daemon did not start."
  exit 1
}

open_firewall() {
  if command -v ufw >/dev/null 2>&1; then
    ufw allow "${NODE_PORT}/tcp" >/dev/null 2>&1 || true
    ok "Порт ${NODE_PORT}/tcp открыт (ufw). / Port opened (ufw)."
  fi
  if command -v firewall-cmd >/dev/null 2>&1; then
    firewall-cmd --permanent --add-port="${NODE_PORT}/tcp" >/dev/null 2>&1 || true
    firewall-cmd --reload >/dev/null 2>&1 || true
    ok "Порт ${NODE_PORT}/tcp открыт (firewalld). / Port opened (firewalld)."
  fi
}

write_files() {
  mkdir -p "${NODE_DIR}"
  cat > "${NODE_DIR}/.env" <<EOF
### Generated by Ghost Sphere — $(date -u +%Y-%m-%dT%H:%M:%SZ)
SECRET_KEY=${SECRET_KEY}
NODE_PORT=${NODE_PORT}
EOF
  chmod 600 "${NODE_DIR}/.env"
  cat > "${NODE_DIR}/docker-compose.yml" <<EOF
services:
  remnanode:
    image: ${IMAGE}
    container_name: ghost-sphere-node
    hostname: ghost-sphere-node
    restart: always
    network_mode: host
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
EOF
  ok "Конфиг записан в ${NODE_DIR}. / Config written to ${NODE_DIR}."
}

main() {
  banner
  need_root

  if [[ -z "${SECRET_KEY:-}" ]]; then
    err "SECRET_KEY не задан. / SECRET_KEY is not set."
    echo -e "  Скопируйте команду целиком из Ghost Sphere → Ноды → Создать."
    echo -e "  Copy the full command from Ghost Sphere → Nodes → Create."
    exit 1
  fi

  ensure_docker
  open_firewall
  write_files

  cd "${NODE_DIR}"
  log "Загружаю образ ноды (может занять 1–2 мин)… / Pulling node image (may take 1–2 min)…"
  compose pull
  log "Запускаю ноду… / Starting the node…"
  compose up -d --remove-orphans

  sleep 3
  if [[ "$(docker inspect -f '{{.State.Running}}' ghost-sphere-node 2>/dev/null || echo false)" != "true" ]]; then
    err "Контейнер не запустился. Логи: / Container failed to start. Logs:"
    compose logs --tail=60 || true
    exit 1
  fi

  echo
  ok "Нода запущена и слушает порт ${NODE_PORT}. / Node is up and listening on ${NODE_PORT}."
  echo -e "${DIM}— Живой лог (≈20с), затем выход. Нода продолжит работать в фоне. —${NC}"
  echo -e "${DIM}— Live log (~20s), then exit. The node keeps running in the background. —${NC}"
  echo
  timeout 20 compose logs -f --tail=40 2>/dev/null || true

  echo
  echo -e "${GREEN}════════════════════════════════════════════════════════════════${NC}"
  ok "Готово! / Done!"
  echo -e "  1) Убедитесь, что порт ${GHOST}${NODE_PORT}/tcp${NC} открыт для IP вашей панели."
  echo -e "     Make sure port ${GHOST}${NODE_PORT}/tcp${NC} is reachable from your panel IP."
  echo -e "  2) В панели Ghost Sphere → Ноды нода поднимется в статус ${GREEN}«подключено»${NC}"
  echo -e "     за 30–60 секунд (панель сама подключится по mTLS)."
  echo -e "     In Ghost Sphere → Nodes the node turns ${GREEN}\"connected\"${NC} within 30–60s."
  echo
  echo -e "  Управление / Manage:  ${CYAN}cd ${NODE_DIR} && docker compose logs -f${NC}"
  echo -e "${GREEN}════════════════════════════════════════════════════════════════${NC}"
}

main "$@"
